### PR TITLE
Fixes error when stop reason missing in response.

### LINKED ISSUE #55: Error: Mistral Models are not working for ChatBedrock & BedrockLLM
This is an example with ChatBedrock.

```python
from langchain_core.messages import HumanMessage
from langchain_aws import ChatBedrock, BedrockLLM

chat = ChatBedrock(
    model_id="mistral.mistral-large-2402-v1:0",
    model_kwargs={"temperature": 0.1},
)
messages = [
    HumanMessage(
        content="Translate this sentence from English to French. I love programming."
    )
]
chat.invoke(messages)
```

Error below:

```
ValueError: Error raised by bedrock service: 'stop_reason'
```

The error is present for all mistral models. It's been a few days already since we detected this error.

### PR DESCRIPTION
**Pull request by 3coins**
Fixes #55, #56.

All integration tests pass.

```
(base) ➜  aws git:(fix-stop-reason-error) make integration_tests             
poetry run pytest tests/integration_tests/
================================================================== test session starts ==================================================================
platform darwin -- Python 3.9.13, pytest-7.4.4, pluggy-1.5.0
rootdir: /Users/pijain/projects/langchain-aws-dev/langchain-aws/libs/aws
configfile: pyproject.toml
plugins: syrupy-4.6.1, anyio-4.3.0, cov-4.1.0, asyncio-0.23.6
asyncio: mode=auto
collected 34 items                                                                                                                                      

tests/integration_tests/test_compile.py .                                                                                                         [  2%]
tests/integration_tests/chat_models/test_bedrock.py ...................                                                                           [ 58%]
tests/integration_tests/embeddings/test_bedrock_embeddings.py .....s...                                                                           [ 85%]
tests/integration_tests/llms/test_sagemaker_endpoint.py ..                                                                                        [ 91%]
tests/integration_tests/retrievers/test_amazon_kendra_retriever.py .                                                                              [ 94%]
tests/integration_tests/retrievers/test_amazon_knowledgebases_retriever.py ..                                                                     [100%]
====================================================== 33 passed, 1 skipped, 2 warnings in 50.68s =======================================================
```

### CODE REVIEW

**Comment by 3coins** [comment]
@arm-diaz @thekrol01 @supreetkt
Can you review and verify this change fixes the issue. Thanks.

**Comment by arm-diaz** [comment]
This looks good. Thank you @3coins !

**Comment by thekrol01** [comment]
Works now. Great work @3coins !

**Comment by supreetkt** [comment]
Tried a few models as well. Looks good to me.

**Comment by nithiyn** [comment]
Thank you!

**Pull request merged**
