### PR TITLE
[#169] Fix the broken in operator in bedrock knowledge base retriever.

### PR DESCRIPTION
**Pull request by renjiexu-amzn**
Fixed the issue mentioned in https://github.com/langchain-ai/langchain-aws/issues/169
Added unit test that would expose the bug in source code
Tested with my service code and it works with the change

### CODE REVIEW

**Comment by felipemonroy** [comment]
@3coins @baskaryan could you review please?

**Review by 3coins — APPROVED** [review]
@renjiexu-amzn 
Thanks for submitting the fix. LGTM!

**Comment by 3coins** [comment]
@renjiexu-amzn 
Can you backport this to v0.1 as well. Thanks for your help.

**Comment by renjiexu-amzn** [comment]
Sure, I'll find some time to backport this to v0.1 branch.

**Comment by renjiexu-amzn** [comment]
BTW, any ETA on when this fix will be released?

**Comment by renjiexu-amzn** [comment]
#243 backport the source code change to v0.1

**Pull request merged**
