### PR TITLE
Improve performance of NeptuneAnalyticsGraph

### PR DESCRIPTION
**Pull request by michaelnchin**
Improved the graph schema retrieval performance of `NeptuneAnalyticsGraph` by using the [pg_schema](https://docs.aws.amazon.com/neptune-analytics/latest/userguide/custom-algorithms-property-graph-schema.html) algorithm.

Before:
Screenshot 2024-12-18 at 8 59 02 PM
After:
Screenshot 2024-12-18 at 8 59 33 PM

### CODE REVIEW

**Review by 3coins — COMMENTED** [review]
@michaelnchin 
Thanks for this performance improvement 🚀. Code looks good, but would be great if one of @krlawrence or @bechbd can review. 

One small question, would users need an option within [NeptuneOpenCypherQAChain](https://python.langchain.com/api_reference/community/chains/langchain_community.chains.graph_qa.neptune_cypher.NeptuneOpenCypherQAChain.html#langchain_community.chains.graph_qa.neptune_cypher.NeptuneOpenCypherQAChain) and [NeptuneSparqlQAChain](https://python.langchain.com/api_reference/community/chains/langchain_community.chains.graph_qa.neptune_sparql.NeptuneSparqlQAChain.html) to allow them to switch to a False option in any scenario?

**Comment by michaelnchin** [comment]
Yes, I think users should be able to control this from the chain level also - will add separate options there.

**Comment by bechbd** [comment]
Along the same note, is there any reason to keep around the old method for an NA graph?  From the end user perspective this should still give the same (or better) result.

**Comment by michaelnchin** [comment]
Discussed offline with @bechbd. While the `pg_schema` algorithm is a brand new feature, all Neptune Analytics graph instances are automatically upgraded to the newest version, and should therefore support it.

Since there are no concerns around backwards compatibility, we will revise this PR to always use `pg_schema` for graph schema retrieval.

**Review by 3coins — APPROVED** [review]

**Comment by krlawrence** [comment]
I took a quick and had no major comments. Thanks for making this improvement.

**Pull request merged**
