### PR TITLE
Fixes streaming for anthropic tool call.

### LINKED ISSUE #80: Recursion depth error: Tool calling with streaming model
When setting the Bedrock model to `streaming=True` and tool calls enabled, it causes a recursion depth error due to stream and generate constantly pointing back to each other.

```
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 432, in _stream
    result = self._generate(
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 501, in _generate
    for chunk in self._stream(messages, stop, run_manager, **kwargs):
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 432, in _stream
    result = self._generate(
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 501, in _generate
    for chunk in self._stream(messages, stop, run_manager, **kwargs):
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 432, in _stream
    result = self._generate(
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 501, in _generate
    for chunk in self._stream(messages, stop, run_manager, **kwargs):
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 427, in _stream
    provider = self._get_provider()
  File "C:\Users\..\AppData\Local\pypoetry\Cache\virtualenvs\..\lib\site-packages\langchain_aws\llms\bedrock.py", line 570, in _get_provider
    if self.model_id.startswith("arn"):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

`llm = ChatBedrock(client=bedrock_client, model_id=model, model_kwargs=model_kwargs, streaming=True)`

```
def _stream(
...

        if "claude-3" in self._get_model():
            if _tools_in_params({**kwargs}):
                result = self._generate(
                    messages, stop=stop, run_manager=run_manager, **kwargs
                )
```

`_stream` points back to `self._generate` if model is claude 3 and tools exist;

```
    def _generate(
...
        if self.streaming:
            response_metadata: List[Dict[str, Any]] = []
            for chunk in self._stream(messages, stop, run_manager, **kwargs):
                completion += chunk.text
                response_metadata.append(chunk.message.response_metadata)
                if "tool_calls" in chunk.message.additional_kwargs.keys():
                    tool_calls = chunk.message.additional_kwargs["tool_calls"]
            llm_output = _combine_generation_info_for_llm_result(
                response_metadata, provider_stop_reason_code
            )
```

`_generate` points back to `_stream()` if `self.streaming` is enabled.

### PR DESCRIPTION
**Pull request by 3coins**
Fixes #80 
Replaces #81

### CODE REVIEW

**Comment by pratik60** [comment]
Any timelines on when we could merge this? The pr looks good to me, and the problem is blocking usage of Bedrock sonnet on our end.

**Comment by xAlstrat** [comment]
Just tried it in langgraph, but I had to adjust a little bit how to use it.

Here are the docs. I'm not sure if part of this PR or not. But I thought it would work seamlessly, and it didn't.

https://langchain-ai.github.io/langgraph/how-tos/streaming-tokens/#streaming-llm-tokens

langgraph==0.1.14
sonnet3.5 through Bedrock

**Comment by Bagel213** [comment]
Just ran into this same problem with Claude with ChatBedrock, good to see it close to be addressed!  Thanks!

**Comment by ccurme** [comment]
@3coins what work remains on this? Can we push it through?

**Comment by Bagel213** [comment]
I am still getting the same error using ChatBedrock with streaming=True.

 File "/home/ec2-user/miniconda3/envs/intrepid/lib/python3.11/site-packages/langchain_aws/llms/bedrock.py", line 594, in _get_provider
    if self.model_id.startswith("arn"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by ccurme** [comment]
> I am still getting the same error using ChatBedrock with streaming=True.
> 
> File "/home/ec2-user/miniconda3/envs/intrepid/lib/python3.11/site-packages/langchain_aws/llms/bedrock.py", line 594, in _get_provider if self.model_id.startswith("arn"): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RecursionError: maximum recursion depth exceeded while calling a Python object
> 
> It works without issue with streaming not set.

Could you try again? This wasn't released at the time of your comment. Just released in langchain-aws==0.1.14.

**Comment by Bagel213** [comment]
Gave it another shot after doing pip3 langchain_aws --upgrade.  Still getting this?
File "/home/ec2-user/miniconda3/envs/intrepid/lib/python3.11/site-packages/langchain_aws/llms/bedrock.py", line 594, in _get_provider
    client_params["endpoint_url"] = values["endpoint_url"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

Do you want the full trace?  This is an anthropic llm calling tools, which then takes multiple data sets as context from the tool.  so not sure if that might be part of the issue or not?

**Pull request merged**
